default_language_version:
    python: python3.10
repos:
  # Run the Ruff linter.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.3
    hooks:
      # Run the Ruff linter.
      - id: ruff
        args: ["dine/", "tests/"]
      # Run the Ruff formatter.
      - id: ruff-format
        args: ["dine/", "tests/"]